import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/header";
import { lemonade } from "./utilities/fonts";
import Footer from "./components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lemonade.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
